name: C# Code Review with OpenAI

on:
  workflow_dispatch:

jobs:
  review-csharp-code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run OpenAI Code Review
      run: python scripts/review_code.py
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    - name: Verificar existencia de review.md
      run: |
        if [ ! -f review.md ]; then
          echo "El archivo review.md no fue generado. Revisa el script review_code.py."
          exit 1
        fi

    - name: Subir artifact de revisión
      uses: actions/upload-artifact@v3
      with:
        name: csharp-review
        path: review.md

    - name: Mostrar Resultado
      run: cat review.md
