name: C# Code Review with OpenAI

on:
  workflow_dispatch:

jobs:
  review-csharp-code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run OpenAI Code Review
      run: python scripts/review_code.py
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    - name: Upload review artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: csharp-review
        path: review.md
